---
# =============================================================================
# ImageStream — stores the built Shopping Cart app image in the internal
# OCP registry. No docker.io required.
# =============================================================================
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: shop-cart-app
  namespace: db2-shop-demo
  labels:
    app: shop-cart
    app.kubernetes.io/part-of: hetero-db2-demo
spec:
  lookupPolicy:
    local: true
---
# =============================================================================
# BuildConfig — S2I build of the Shopping Cart app server
#
# Base image: registry.redhat.io/ubi9/python-311:latest
#   (Red Hat UBI9 Python 3.11 — multi-arch, supports amd64 + ppc64le)
#   Build pod is pinned to the Intel (amd64) node → produces an amd64 image.
#
# Source: local binary build — the app/ directory is uploaded via `oc start-build`
#
# Output: pushed to the internal ImageStream shop-cart-app:latest
# =============================================================================
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: shop-cart-app
  namespace: db2-shop-demo
  labels:
    app: shop-cart
    app.kubernetes.io/part-of: hetero-db2-demo
spec:
  # Build runs on the Intel (amd64) node so the resulting image is amd64
  nodeSelector:
    kubernetes.io/arch: amd64
  source:
    type: Binary
    binary: {}
  strategy:
    type: Source
    sourceStrategy:
      # Use registry.redhat.io/ubi9/python-311 directly — multi-arch (amd64 + ppc64le)
      # The build pod runs on the amd64 (Intel) node so the amd64 variant is pulled.
      from:
        kind: DockerImage
        name: "registry.redhat.io/ubi9/python-311:latest"
      env:
        - name: PIP_NO_CACHE_DIR
          value: "1"
  output:
    to:
      kind: ImageStreamTag
      name: "shop-cart-app:latest"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2