# IBM Entitlement Key Secret for pulling Db2 images from cp.icr.io
# The Db2 Operator uses this secret to pull images during instance creation
#
# IMPORTANT: Replace <YOUR_IBM_ENTITLEMENT_KEY> with your actual IBM Entitlement Key
# Obtain from: https://myibm.ibm.com/products-services/containerlibrary
#
# If the IBM Entitlement Key is already in the OCP global pull secret (openshift-config/pull-secret),
# you still need this namespace-level secret for the Db2 Operator to pull images.
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: ecommerce-demo
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded docker config JSON with cp.icr.io credentials
  # Generate with:
  #   kubectl create secret docker-registry ibm-entitlement-key \
  #     --docker-server=cp.icr.io \
  #     --docker-username=cp \
  #     --docker-password=<YOUR_IBM_ENTITLEMENT_KEY> \
  #     --namespace=ecommerce-demo \
  #     --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6eyJjcC5pY3IuaW8iOnsidXNlcm5hbWUiOiJjcCIsInBhc3N3b3JkIjoiPFlPVVJfSUJNX0VOVElUTEVNRU5UX0tFWT4iLCJhdXRoIjoiWW1Wc1lYa3ZQbGxQVlZKZlNVSk5YMFZPVkVsVVRFVk9WRTFGVVU1VVgwdEZXVDQ9In19fQ==