apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: db2u-ecommerce
  namespace: ecommerce-demo
spec:
  # License: Community Edition (free, no entitlement key required)
  # Only accept:true is needed — do NOT set license.value for Community edition
  # license.value expects a real IBM license certificate file content, not a string
  license:
    accept: true

  # Database type and configuration
  environment:
    dbType: db2oltp
    database:
      name: SHOPDB
    # instance password is managed via Secret: db2u-ecommerce-secret

  # Node affinity: schedule Db2 pods on IBM Power (ppc64le) node
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - ppc64le
              - key: workload-type
                operator: In
                values:
                  - database

  # Single-node deployment
  size: 1

  # Db2 version
  # Version must match keys in db2u-release ConfigMap (operator-managed)
  version: "s11.5.9.0-cn7"

  # Resource requests/limits for Db2 engine pod
  podConfig:
    db2u:
      resource:
        db2u:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"

  # Persistent storage volumes
  storage:
    - name: meta
      type: create
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - name: data
      type: create
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    - name: backup
      type: create
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - name: tempts
      type: create
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - name: archivelogs
      type: create
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi